language: node_js
node_js:
    - "0.8"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq  libgeos-dev

before_script:
    - python bootstrap.py --version 1.5.2 --distribute --download-base http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py
    - buildout/bin/buildout

script:
    - buildout/bin/buildout install js-tests

notifications:
    email:
        recipients:
            - git-mf-next@bgdi.ch
