before_install:
    - "sudo npm install -g karma"
    - "git submodule update --init"
    - "python bootstrap.py --version 1.5.2 --distribute --download-base http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py"

before_script:
    - "buildout/bin/buildout"

script:
    - "karma start geoadmin/static/lib/geoadmin/test/karma.conf.js --single-run"


